/**
 * Pin test for /plan step 5 (issue #511 / generacy#899).
 *
 * Guards against regression: the plan phase must write per-feature tech context to
 * `specs/<feature>/stack.md` and must NEVER reintroduce the old `update_agent` /
 * repo-root `CLAUDE.md` behavior. The two byte-identical `plan.md` copies must not drift.
 *
 * This is a drift audit, not a smoke test. Do NOT weaken or delete an assertion to make
 * it pass — if step 5's contract changes, re-pin the assertions to the new contract in
 * the same PR (see contracts/plan-step5.md).
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { describe, it, expect } from 'vitest';

const testDir = dirname(fileURLToPath(import.meta.url));
const canonicalPath = join(testDir, '../commands/plan.md');
const mirrorPath = join(testDir, '../../claude-plugin-agency-spec-kit/commands/plan.md');

const canonical = readFileSync(canonicalPath, 'utf8');
const mirror = readFileSync(mirrorPath, 'utf8');

// P1–P4 from contracts/plan-step5.md — must be present verbatim in both copies.
const PRESENCE = [
  'specs/<feature>/stack.md', // P1
  'Generated by /plan — do not hand-edit.', // P2 (exact, em dash U+2014)
  'Fully overwrite', // P3 (overwrite semantics)
  'never append', // P3 (overwrite semantics)
  // P4 — the single prohibition sentence:
  'must NEVER modify repo-root agent-context files (`CLAUDE.md`, `AGENTS.md`, `GEMINI.md`, `.github/copilot-instructions.md`)',
];

// The single sentence permitted to contain agent-context filenames / the phrase
// "agent context". Every B2/B3 match must fall inside this sentence's [start, end).
const PROHIBITION_SENTENCE =
  'must NEVER modify repo-root agent-context files (`CLAUDE.md`, `AGENTS.md`, `GEMINI.md`, `.github/copilot-instructions.md`)';

const BANNED_EVERYWHERE = /update[_-]?agent/gi; // B1

const SCOPED_BANS: RegExp[] = [
  /claude\.md/gi, // B2
  /agents\.md/gi, // B2
  /gemini\.md/gi, // B2
  /copilot-instructions\.md/gi, // B2
  /agent[\s-]context/gi, // B3 (catches hyphenated variant)
];

function allMatchIndices(text: string, pattern: RegExp): number[] {
  const re = new RegExp(pattern.source, pattern.flags.includes('g') ? pattern.flags : pattern.flags + 'g');
  const indices: number[] = [];
  let m: RegExpExecArray | null;
  while ((m = re.exec(text)) !== null) {
    indices.push(m.index);
    if (m.index === re.lastIndex) re.lastIndex++; // guard against zero-width
  }
  return indices;
}

describe.each([
  ['canonical', canonical],
  ['mirror', mirror],
])('plan.md pin (%s copy)', (_label, content) => {
  it.each(PRESENCE)('contains pinned string: %s', (needle) => {
    expect(content).toContain(needle);
  });

  it('never mentions update_agent anywhere (B1)', () => {
    expect(allMatchIndices(content, BANNED_EVERYWHERE)).toHaveLength(0);
  });

  it('contains exactly one prohibition sentence', () => {
    expect(allMatchIndices(content, new RegExp(escapeRegExp(PROHIBITION_SENTENCE)))).toHaveLength(1);
  });

  it('confines agent-context filenames / phrase to the prohibition sentence (B2/B3)', () => {
    const start = content.indexOf(PROHIBITION_SENTENCE);
    expect(start).toBeGreaterThanOrEqual(0);
    const end = start + PROHIBITION_SENTENCE.length;

    for (const pattern of SCOPED_BANS) {
      for (const idx of allMatchIndices(content, pattern)) {
        expect(
          idx >= start && idx < end,
          `match of ${pattern} at index ${idx} falls outside the prohibition sentence [${start}, ${end})`,
        ).toBe(true);
      }
    }
  });
});

describe('plan.md copies', () => {
  it('are byte-identical', () => {
    expect(canonical).toBe(mirror);
  });
});

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
